services:
  django-web:
    image: ghcr.io/imed-capstone/inventory-manager:main
    container_name: django-docker
    ports:
      - "8999:8000"
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DEBUG: ${DEBUG}
      DJANGO_LOGLEVEL: ${DJANGO_LOGLEVEL}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      DATABASE_ENGINE: ${DATABASE_ENGINE}
      DATABASE_NAME: ${DATABASE_NAME}
    volumes:
      - ./data:/data
    env_file:
      - .env

  docs-server:
    image: ghcr.io/imed-capstone/inventory-manager:main
    container_name: docs-server
    entrypoint: /bin/sh
    command: -c "cd /app/docs/_build/html && test -f index.html && exec python -m http.server 8010 || { echo 'index.html not found'; exit 1; }"
    ports:
      - "8998:8010"
    env_file:
      - .env
    profiles:
      - docs
