# Generated by Django 5.1.7 on 2025-04-01 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ItemModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item", models.CharField(max_length=200)),
                ("mfr", models.CharField(max_length=200)),
                ("mfr_cat", models.CharField(max_length=200)),
                ("vendor", models.CharField(max_length=200)),
                ("vend_cat", models.CharField(max_length=200)),
                ("descr", models.CharField(max_length=200)),
                ("recv_qty", models.PositiveIntegerField()),
                ("um", models.CharField(max_length=200)),
                ("price", models.FloatField()),
                ("total_cost", models.FloatField()),
                ("expr1010", models.CharField(max_length=200)),
                ("po_no", models.CharField(max_length=200)),
                ("po_date", models.DateTimeField()),
                ("vend_code", models.CharField(max_length=200)),
                ("item_no", models.CharField(max_length=200)),
                ("dbo_vend_name", models.CharField(max_length=200)),
                ("expr1016", models.CharField(max_length=200)),
                ("expr1017", models.IntegerField()),
            ],
        ),
    ]
