# Generated by Django 5.1.7 on 2025-04-01 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_itemmodel_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="price",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
