# Generated by Django 5.1.7 on 2025-04-01 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_item_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="recv_qty",
            field=models.IntegerField(),
        ),
    ]
