# Generated by Django 5.1.7 on 2025-04-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_item_recv_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='par_level',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
    ]
