# Generated by Django 5.1.7 on 2025-04-27 18:02

import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_item_price_currency_alter_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='external_url',
            field=models.URLField(default='https://accessgudid.nlm.nih.gov/resources/developers/v3/device_lookup_api'),
        ),
        migrations.AlterField(
            model_name='item',
            name='dbo_vend_name',
            field=models.CharField(max_length=200, verbose_name='dbo_VEND.NAME'),
        ),
        migrations.AlterField(
            model_name='item',
            name='descr',
            field=models.CharField(max_length=200, verbose_name='DESCR'),
        ),
        migrations.AlterField(
            model_name='item',
            name='expr1010',
            field=models.CharField(max_length=200, verbose_name='Expr1010'),
        ),
        migrations.AlterField(
            model_name='item',
            name='expr1016',
            field=models.CharField(max_length=200, verbose_name='Expr1016'),
        ),
        migrations.AlterField(
            model_name='item',
            name='expr1017',
            field=models.IntegerField(verbose_name='Expr1017'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item',
            field=models.CharField(max_length=200, verbose_name='ITEM'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_no',
            field=models.CharField(max_length=200, verbose_name='ITEM_NO'),
        ),
        migrations.AlterField(
            model_name='item',
            name='mfr',
            field=models.CharField(max_length=200, verbose_name='MFR'),
        ),
        migrations.AlterField(
            model_name='item',
            name='mfr_cat',
            field=models.CharField(max_length=200, verbose_name='MFR CAT'),
        ),
        migrations.AlterField(
            model_name='item',
            name='po_date',
            field=models.DateTimeField(verbose_name='PO_DATE'),
        ),
        migrations.AlterField(
            model_name='item',
            name='po_no',
            field=models.CharField(max_length=200, verbose_name='PO_NO'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=14, null=True, verbose_name='PRICE'),
        ),
        migrations.AlterField(
            model_name='item',
            name='recv_qty',
            field=models.IntegerField(verbose_name='RECV QTY'),
        ),
        migrations.AlterField(
            model_name='item',
            name='total_cost',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=14, verbose_name='TOTAL COST'),
        ),
        migrations.AlterField(
            model_name='item',
            name='um',
            field=models.CharField(max_length=200, verbose_name='UM'),
        ),
        migrations.AlterField(
            model_name='item',
            name='vend_cat',
            field=models.CharField(max_length=200, verbose_name='VEND CAT'),
        ),
        migrations.AlterField(
            model_name='item',
            name='vend_code',
            field=models.CharField(max_length=200, verbose_name='VEND_CODE'),
        ),
        migrations.AlterField(
            model_name='item',
            name='vendor',
            field=models.CharField(max_length=200, verbose_name='VENDOR'),
        ),
    ]
