# Generated by Django 5.1.7 on 2025-05-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_item_external_url_alter_item_dbo_vend_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='expr1016',
        ),
        migrations.AddField(
            model_name='item',
            name='dbo_cc_name',
            field=models.CharField(default='', max_length=200, verbose_name='dbo_CC.NAME'),
            preserve_default=False,
        ),
    ]
