# Generated by Django 5.1.7 on 2025-05-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_item_expr1016_item_dbo_cc_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='expr1017',
        ),
        migrations.AddField(
            model_name='item',
            name='acct_no',
            field=models.IntegerField(default=0, verbose_name='ACCT_NO'),
        ),
        migrations.AddField(
            model_name='item',
            name='rcv_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='RCV_DATE'),
        ),
    ]
