# Generated by Django 5.1.7 on 2025-05-10 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_item_expr1017_item_acct_no_item_rcv_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Order',
        ),
    ]
