# Generated by Django 5.1.7 on 2025-05-10 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_item_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200, verbose_name='ITEM')),
                ('item_no', models.CharField(max_length=200, verbose_name='ITEM_NO')),
                ('mfr', models.CharField(max_length=200, verbose_name='MFR')),
                ('mfr_cat', models.CharField(max_length=200, verbose_name='MFR CAT')),
                ('descr', models.CharField(max_length=200, verbose_name='DESCR')),
                ('par_level', models.PositiveIntegerField(blank=True, default=1)),
                ('external_url', models.URLField(default='https://accessgudid.nlm.nih.gov/resources/developers/v3/device_lookup_api')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='descr',
        ),
        migrations.RemoveField(
            model_name='order',
            name='external_url',
        ),
        migrations.RemoveField(
            model_name='order',
            name='item_no',
        ),
        migrations.RemoveField(
            model_name='order',
            name='mfr',
        ),
        migrations.RemoveField(
            model_name='order',
            name='mfr_cat',
        ),
        migrations.RemoveField(
            model_name='order',
            name='par_level',
        ),
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.item'),
        ),
    ]
