# Generated by Django 5.1.7 on 2025-05-10 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_item_remove_order_descr_remove_order_external_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='item',
            new_name='order_item',
        ),
    ]
