# Generated by Django 5.1.7 on 2025-07-31 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_item_remove_order_descr_remove_order_external_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('change', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out')], max_length=3)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.item')),
            ],
        ),
        migrations.CreateModel(
            name='ParLevelTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('previous_par', models.PositiveIntegerField()),
                ('new_par', models.PositiveIntegerField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='par_changes', to='core.item')),
            ],
        ),
    ]
