# Generated by Django 5.1.7 on 2025-08-29 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_itemtransaction_parleveltransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_identifier', models.CharField(max_length=200, verbose_name='DI')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='current_count',
            field=models.IntegerField(default=0, verbose_name='CURR COUNT'),
        ),
        migrations.AddField(
            model_name='item',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='core.device'),
        ),
    ]
