# Generated by Django 5.1.7 on 2025-08-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_device_item_current_count_item_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_name',
            field=models.CharField(max_length=200, null=True, verbose_name='NAME'),
        ),
        migrations.AddField(
            model_name='device',
            name='manufacturer',
            field=models.CharField(max_length=200, null=True, verbose_name='MANUFACTURER'),
        ),
        migrations.AddField(
            model_name='item',
            name='exp_date',
            field=models.DateField(null=True, verbose_name='EXP DATE'),
        ),
    ]
