# Generated by Django 5.1.7 on 2025-08-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_device_device_name_device_manufacturer_item_exp_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='current_count',
            field=models.IntegerField(default=0, verbose_name='CURR COUNT'),
        ),
    ]
